[opener]
text = [{ run = 'nvim "$@"', block = true }]

[[manager.prepend_keymap]]
on  = "y"
run = [ 'shell -- echo "$@" | xclip -i -selection clipboard -t text/uri-list', "yank" ]


# Gruvbox

[theme]
name = "gruvbox-dark"

# Основные цвета
primary = { fg = "#ebdbb2", bg = "#282828" }  # foreground и background
secondary = { fg = "#a89984" }                 # второстепенный текст
hovered = { fg = "#fabd2f", bg = "#3c3836" }   # выделение при наведении
selected = { fg = "#d3869b", bg = "#458588" }  # выбранные элементы

# Статус-бар
status = { fg = "#1d2021", bg = "#d79921" }
status_unfocused = { fg = "#1d2021", bg = "#a89984" }

# Границы и разделители
border = { fg = "#665c54" }
split = { fg = "#665c54" }

# Иконки и типы файлов
file = { fg = "#ebdbb2" }                     # обычные файлы
directory = { fg = "#83a598", bold = true }    # директории
symlink = { fg = "#8ec07c", italic = true }    # симлинки
executable = { fg = "#b8bb26" }               # исполняемые файлы

# Дополнительные элементы
progress = { fg = "#b8bb26" }                # индикатор прогресса
preview = { border = "#d3869b" }             # рамка превью
